services:
    mbhs.helper:
      class: MBHS\Bundle\BaseBundle\Service\Helper

    mbhs.epochta:
      class: MBHS\Bundle\BaseBundle\Service\Epochta
      arguments: [@kernel]

    mbh.get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }

    doctrine_odm.mongodb.validator.unique:
          class: MBHS\Bundle\BaseBundle\Validator\Constraints\UniqueEntityValidator
          arguments:
            - @doctrine_mongodb
          tags:
            - { name: validator.constraint_validator, alias: doctrine_odm.mongodb.unique }

    #Admin
    sonata.admin.log:
      class: MBHS\Bundle\BaseBundle\Admin\Log
      tags:
          - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Logs", label: "Logs"}
      arguments:
          - ~
          - MBHS\Bundle\BaseBundle\Document\Log
          - ~
      calls:
          - [ setTranslationDomain, [MBHSBaseBundle]]

    sonata.admin.version:
          class: MBHS\Bundle\BaseBundle\Admin\Version
          tags:
              - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Clients", label: "Versions"}
          arguments:
              - ~
              - MBHS\Bundle\BaseBundle\Document\Version
              - ~
          calls:
              - [ setTranslationDomain, [MBHSBaseBundle]]

    sonata.admin.user:
          class: MBHS\Bundle\BaseBundle\Admin\User
          tags:
              - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Auth", label: "Users"}
          arguments:
              - ~
              - MBHS\Bundle\BaseBundle\Document\User
              - ~
          calls:
              - [ setTranslationDomain, [MBHSBaseBundle]]
              - [ setUserManager, ["@fos_user.user_manager"]]