services:
    mbhs.helper:
      class: MBHS\Bundle\BaseBundle\Service\Helper

    mbhs.epochta:
      class: MBHS\Bundle\BaseBundle\Service\Epochta
      arguments: [@kernel]

    #Admin
    sonata.admin.log:
      class: MBHS\Bundle\BaseBundle\Admin\Log
      tags:
          - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Logs", label: "Logs"}
      arguments:
          - ~
          - MBHS\Bundle\BaseBundle\Document\Log
          - ~
      calls:
          - [ setTranslationDomain, [MBHSBaseBundle]]

    sonata.admin.user:
          class: MBHS\Bundle\BaseBundle\Admin\User
          tags:
              - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Auth", label: "Users"}
          arguments:
              - ~
              - MBHS\Bundle\BaseBundle\Document\User
              - ~
          calls:
              - [ setTranslationDomain, [MBHSBaseBundle]]
              - [ setUserManager, ["@fos_user.user_manager"]]