services:
  mbhs.request:
          class: MBHS\Bundle\ClientBundle\Service\Request
          arguments: [@service_container]

  #Admin
  sonata.admin.pirate_client:
          class: MBHS\Bundle\ClientBundle\Admin\PirateClient
          tags:
              - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Logs", label: "Pirates"}
          arguments:
              - ~
              - MBHS\Bundle\ClientBundle\Document\PirateClient
              - ~
          calls:
              - [ setTranslationDomain, [MBHSClientBundle]]

  sonata.admin.client:
            class: MBHS\Bundle\ClientBundle\Admin\Client
            tags:
                - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Clients", label: "Clients", icon: "<i class='fa fa-users'></i>" }
            arguments:
                - ~
                - MBHS\Bundle\ClientBundle\Document\Client
                - ~
            calls:
                - [ setTranslationDomain, [MBHSClientBundle]]